// src/narrative/moduleRegistry.js
//
// Prompt Module Library for the Narrative Master system.
// Each module is an executable narrative operation — not a theme label.
// Modules are selected by the Narrative Master and composed into scene instructions.

/**
 * @typedef {{
 *   id: string,
 *   instruction: string,
 *   purpose: 'introduce' | 'complicate' | 'escalate' | 'converge' | 'resolve',
 *   emotionalMode: 'tender' | 'eerie' | 'tense' | 'playful' | 'mournful' | 'reflective',
 *   narrativeFunction: 'reveal' | 'withhold' | 'test' | 'tempt' | 'mirror' | 'destabilize' | 'narrow' | 'echo',
 *   pace: 'slow' | 'medium' | 'abrupt',
 *   applicablePhase: Array<'opening' | 'pressure' | 'convergence' | 'cooldown'>,
 *   tensionRange: [number, number],
 *   affectedDimensions: string[]
 * }} PromptModule
 */

/** @type {PromptModule[]} */
export const PROMPT_MODULES = [

  // ── OPENING ─────────────────────────────────────────────────────────────────

  {
    id: 'plant_warm_constraint',
    instruction: 'Make the player feel welcomed or cared for in a way that also restricts movement. Warmth and limitation come from the same source — do not separate them.',
    purpose: 'introduce',
    emotionalMode: 'tender',
    narrativeFunction: 'test',
    pace: 'slow',
    applicablePhase: ['opening'],
    tensionRange: [0, 4],
    affectedDimensions: ['intimacy', 'agency', 'obligation'],
  },
  {
    id: 'introduce_unreliable_ally',
    instruction: 'Introduce a character who offers help, but whose exact terms or motives are not stated. Leave one deliberate gap. Do not fill it.',
    purpose: 'introduce',
    emotionalMode: 'eerie',
    narrativeFunction: 'withhold',
    pace: 'medium',
    applicablePhase: ['opening', 'pressure'],
    tensionRange: [0, 5],
    affectedDimensions: ['trust', 'mystery'],
  },
  {
    id: 'seed_obligation',
    instruction: 'Establish a favor, debt, or unspoken promise the player now carries. Make the obligation feel earned — arising naturally from the scene, not imposed.',
    purpose: 'introduce',
    emotionalMode: 'reflective',
    narrativeFunction: 'test',
    pace: 'slow',
    applicablePhase: ['opening', 'pressure'],
    tensionRange: [0, 6],
    affectedDimensions: ['obligation', 'trust', 'agency'],
  },
  {
    id: 'open_mystery_hook',
    instruction: 'Plant one observable, concrete detail with no explanation. Name it precisely. Do not foreshadow or explain it. Leave it sitting in the scene without comment.',
    purpose: 'introduce',
    emotionalMode: 'eerie',
    narrativeFunction: 'withhold',
    pace: 'slow',
    applicablePhase: ['opening'],
    tensionRange: [0, 4],
    affectedDimensions: ['mystery'],
  },
  {
    id: 'establish_arrival_cost',
    instruction: "Show that the player's presence here has already changed something for someone else. The cost of arriving is visible before anything is explained.",
    purpose: 'introduce',
    emotionalMode: 'mournful',
    narrativeFunction: 'reveal',
    pace: 'medium',
    applicablePhase: ['opening'],
    tensionRange: [1, 5],
    affectedDimensions: ['distance', 'obligation'],
  },

  // ── COMPLICATION ─────────────────────────────────────────────────────────────

  {
    id: 'care_as_constraint',
    instruction: "Present concern or affection from an NPC as something that limits the player's options. Caring and controlling arise from the same gesture — do not separate them.",
    purpose: 'complicate',
    emotionalMode: 'tender',
    narrativeFunction: 'test',
    pace: 'slow',
    applicablePhase: ['pressure'],
    tensionRange: [2, 6],
    affectedDimensions: ['intimacy', 'agency', 'obligation'],
  },
  {
    id: 'complicate_trust',
    instruction: 'Introduce one piece of information that makes a trusted figure slightly less certain. Not a betrayal — a crack. Do not resolve or explain it this scene.',
    purpose: 'complicate',
    emotionalMode: 'eerie',
    narrativeFunction: 'destabilize',
    pace: 'medium',
    applicablePhase: ['pressure'],
    tensionRange: [3, 7],
    affectedDimensions: ['trust', 'mystery'],
  },
  {
    id: 'force_tradeoff',
    instruction: 'Reveal that advancing one objective damages another. Make both costs specific and concrete — not abstract. The player must choose which loss to accept.',
    purpose: 'escalate',
    emotionalMode: 'tense',
    narrativeFunction: 'test',
    pace: 'abrupt',
    applicablePhase: ['pressure', 'convergence'],
    tensionRange: [4, 8],
    affectedDimensions: ['agency', 'obligation', 'inevitability'],
  },
  {
    id: 'destabilize_loyalty',
    instruction: "Raise a quiet doubt about whether an ally's stated motives match their actual ones. Show this through action or omission — not accusation. Leave it unresolved.",
    purpose: 'complicate',
    emotionalMode: 'eerie',
    narrativeFunction: 'destabilize',
    pace: 'slow',
    applicablePhase: ['pressure'],
    tensionRange: [3, 7],
    affectedDimensions: ['trust', 'distance', 'mystery'],
  },
  {
    id: 'obligation_surfaces',
    instruction: 'Bring a past promise, debt, or favor back into the scene. It is now inconvenient or costly. Let the player feel the weight without being told what to do about it.',
    purpose: 'complicate',
    emotionalMode: 'mournful',
    narrativeFunction: 'echo',
    pace: 'medium',
    applicablePhase: ['pressure', 'convergence'],
    tensionRange: [2, 8],
    affectedDimensions: ['obligation', 'agency'],
  },
  {
    id: 'quiet_wrongness',
    instruction: "Add one small detail to the environment or an NPC's behavior that doesn't fit the scene's logic. Present it without explanation. Let it sit unaddressed.",
    purpose: 'complicate',
    emotionalMode: 'eerie',
    narrativeFunction: 'withhold',
    pace: 'slow',
    applicablePhase: ['opening', 'pressure'],
    tensionRange: [1, 6],
    affectedDimensions: ['mystery', 'distance'],
  },
  {
    id: 'reveal_hidden_cost',
    instruction: "Show the consequence of the player's last meaningful choice — concretely, without editorializing. Present the cost as fact. Let the player absorb it.",
    purpose: 'complicate',
    emotionalMode: 'mournful',
    narrativeFunction: 'reveal',
    pace: 'medium',
    applicablePhase: ['pressure', 'convergence'],
    tensionRange: [3, 8],
    affectedDimensions: ['obligation', 'inevitability', 'distance'],
  },

  // ── ESCALATION ───────────────────────────────────────────────────────────────

  {
    id: 'narrow_options',
    instruction: 'Close one path the player might expect to use. Make the narrowing feel natural — a door that locked, a person who left, a resource that ran out.',
    purpose: 'escalate',
    emotionalMode: 'tense',
    narrativeFunction: 'narrow',
    pace: 'medium',
    applicablePhase: ['pressure', 'convergence'],
    tensionRange: [4, 8],
    affectedDimensions: ['agency', 'inevitability'],
  },
  {
    id: 'convergence_narrowing',
    instruction: 'Remove an apparent escape route. The available forward path must now be chosen from what remains. Each remaining option must feel real and carry cost.',
    purpose: 'converge',
    emotionalMode: 'tense',
    narrativeFunction: 'narrow',
    pace: 'abrupt',
    applicablePhase: ['convergence'],
    tensionRange: [5, 10],
    affectedDimensions: ['agency', 'inevitability'],
  },
  {
    id: 'irreversible_moment',
    instruction: 'Push the scene to a point of commitment. The player must choose or act — neutrality is not available. Something cannot be unsaid or undone.',
    purpose: 'converge',
    emotionalMode: 'tense',
    narrativeFunction: 'test',
    pace: 'abrupt',
    applicablePhase: ['convergence'],
    tensionRange: [6, 10],
    affectedDimensions: ['agency', 'inevitability', 'trust'],
  },
  {
    id: 'pressure_on_relationship',
    instruction: 'Put two relationships in conflict. Prioritizing one damages the other. Force the player to reveal, through action, which matters more.',
    purpose: 'escalate',
    emotionalMode: 'tense',
    narrativeFunction: 'test',
    pace: 'medium',
    applicablePhase: ['pressure', 'convergence'],
    tensionRange: [4, 9],
    affectedDimensions: ['trust', 'intimacy', 'obligation'],
  },
  {
    id: 'false_relief',
    instruction: 'Offer what appears to be resolution or safety. Let the player feel briefly secure. Make it a surface that will crack — but not yet, not this scene.',
    purpose: 'complicate',
    emotionalMode: 'eerie',
    narrativeFunction: 'tempt',
    pace: 'slow',
    applicablePhase: ['pressure', 'convergence'],
    tensionRange: [4, 8],
    affectedDimensions: ['mystery', 'inevitability'],
  },
  {
    id: 'memory_echo',
    instruction: 'Reference a concrete earlier moment — something the player did, said, or chose — and show how it reads differently from this new vantage. Do not explain the shift.',
    purpose: 'complicate',
    emotionalMode: 'reflective',
    narrativeFunction: 'echo',
    pace: 'slow',
    applicablePhase: ['pressure', 'convergence'],
    tensionRange: [3, 9],
    affectedDimensions: ['inevitability', 'obligation', 'distance'],
  },
  {
    id: 'stakes_made_concrete',
    instruction: 'Make the consequence of failure immediate and specific. Give it a name and a shape. Abstract risk becomes real cost with a face attached.',
    purpose: 'escalate',
    emotionalMode: 'tense',
    narrativeFunction: 'reveal',
    pace: 'abrupt',
    applicablePhase: ['pressure', 'convergence'],
    tensionRange: [5, 10],
    affectedDimensions: ['inevitability', 'agency'],
  },

  // ── RESOLUTION ───────────────────────────────────────────────────────────────

  {
    id: 'close_thread',
    instruction: 'Bring one active narrative thread to a concrete ending. Not ambiguous. Not deferred. It closes — even if the closure is painful or incomplete.',
    purpose: 'resolve',
    emotionalMode: 'mournful',
    narrativeFunction: 'reveal',
    pace: 'medium',
    applicablePhase: ['convergence', 'cooldown'],
    tensionRange: [5, 10],
    affectedDimensions: ['inevitability', 'distance'],
  },
  {
    id: 'cost_lands_quietly',
    instruction: "Let the consequence of a past choice land without drama. No commentary — just reality. The player sees what their decision cost, plainly.",
    purpose: 'resolve',
    emotionalMode: 'mournful',
    narrativeFunction: 'reveal',
    pace: 'slow',
    applicablePhase: ['convergence', 'cooldown'],
    tensionRange: [3, 9],
    affectedDimensions: ['obligation', 'distance', 'inevitability'],
  },
  {
    id: 'trust_test_result',
    instruction: 'Show whether a prior trust-building action paid off or failed. The result must be concrete, visible, and not softened or hedged.',
    purpose: 'resolve',
    emotionalMode: 'tense',
    narrativeFunction: 'reveal',
    pace: 'abrupt',
    applicablePhase: ['convergence'],
    tensionRange: [4, 10],
    affectedDimensions: ['trust', 'inevitability'],
  },
  {
    id: 'earned_intimacy',
    instruction: 'Let a relationship shift to a genuinely different level — one earned through earlier play, not given freely. Make the shift exact and felt, not stated.',
    purpose: 'resolve',
    emotionalMode: 'tender',
    narrativeFunction: 'reveal',
    pace: 'slow',
    applicablePhase: ['pressure', 'convergence', 'cooldown'],
    tensionRange: [2, 7],
    affectedDimensions: ['intimacy', 'trust'],
  },
  {
    id: 'goodbye_weight',
    instruction: 'Make a departure, farewell, or loss feel expensive — not melodramatic, just true. The weight comes from what was built between these people in earlier scenes.',
    purpose: 'resolve',
    emotionalMode: 'mournful',
    narrativeFunction: 'mirror',
    pace: 'slow',
    applicablePhase: ['convergence', 'cooldown'],
    tensionRange: [4, 9],
    affectedDimensions: ['distance', 'intimacy', 'inevitability'],
  },

  // ── REFLECTIVE ───────────────────────────────────────────────────────────────

  {
    id: 'quiet_intimacy_scene',
    instruction: 'Create a scene of low external pressure where one character reveals something true. Let the intimacy be justified by what came before it — not by narrative convenience.',
    purpose: 'introduce',
    emotionalMode: 'tender',
    narrativeFunction: 'reveal',
    pace: 'slow',
    applicablePhase: ['opening', 'pressure', 'cooldown'],
    tensionRange: [0, 5],
    affectedDimensions: ['intimacy', 'trust'],
  },
  {
    id: 'mirror_moment',
    instruction: 'Have a character reflect back something the player did or said — with a framing the player might not have expected. Not accusation. Not praise. Just seeing.',
    purpose: 'complicate',
    emotionalMode: 'reflective',
    narrativeFunction: 'mirror',
    pace: 'slow',
    applicablePhase: ['pressure', 'convergence'],
    tensionRange: [3, 8],
    affectedDimensions: ['trust', 'distance', 'intimacy'],
  },
  {
    id: 'silence_as_information',
    instruction: 'Give weight to what is NOT said. Let a withheld response, an unasked question, or a deliberate pause carry the meaning of the scene.',
    purpose: 'complicate',
    emotionalMode: 'eerie',
    narrativeFunction: 'withhold',
    pace: 'slow',
    applicablePhase: ['opening', 'pressure', 'convergence'],
    tensionRange: [1, 7],
    affectedDimensions: ['mystery', 'distance', 'trust'],
  },
  {
    id: 'introspection_beat',
    instruction: 'Create space for the player to feel what happened — low action, one honest moment. A decision or loss is registered, not acted on. Let it land.',
    purpose: 'resolve',
    emotionalMode: 'reflective',
    narrativeFunction: 'mirror',
    pace: 'slow',
    applicablePhase: ['pressure', 'cooldown'],
    tensionRange: [0, 6],
    affectedDimensions: ['intimacy', 'distance'],
  },

  // ── SPECIAL ──────────────────────────────────────────────────────────────────

  {
    id: 'tempt_defection',
    instruction: 'Offer the player something they genuinely want — at the cost of a prior loyalty or commitment. Make the temptation real. Make the cost visible. Do not editorialize.',
    purpose: 'escalate',
    emotionalMode: 'tense',
    narrativeFunction: 'tempt',
    pace: 'abrupt',
    applicablePhase: ['pressure', 'convergence'],
    tensionRange: [5, 10],
    affectedDimensions: ['trust', 'obligation', 'agency'],
  },
  {
    id: 'departure_cost',
    instruction: 'Make leaving a situation feel emotionally costly, even if leaving is clearly the right thing to do. The cost is relational — not physical danger.',
    purpose: 'resolve',
    emotionalMode: 'mournful',
    narrativeFunction: 'test',
    pace: 'medium',
    applicablePhase: ['pressure', 'convergence', 'cooldown'],
    tensionRange: [3, 8],
    affectedDimensions: ['distance', 'intimacy', 'obligation'],
  },
  {
    id: 'reframe_antagonist',
    instruction: "Introduce information that makes an opposing character's position understandable — not sympathetic, just coherent. The player sees why they do what they do.",
    purpose: 'complicate',
    emotionalMode: 'reflective',
    narrativeFunction: 'reveal',
    pace: 'medium',
    applicablePhase: ['pressure', 'convergence'],
    tensionRange: [4, 8],
    affectedDimensions: ['trust', 'mystery', 'distance'],
  },
];
